global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # مراقبة Prometheus نفسه
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # مراقبة تطبيق Flask
  - job_name: 'flask-app'
    static_configs:
      - targets: ['web:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # مراقبة PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

  # مراقبة Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # مراقبة Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  # مراقبة Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
