services:
  - type: web
    name: full-accounting-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python accounting_system_complete.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://USER:PASSWORD@HOST/DBNAME
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

