services:
  - type: web
    name: complete-accounting-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn accounting_system_complete:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///accounting_complete.db

